<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>Config</string>
	</array>
	<key>name</key>
	<string>Mellanox</string>
	<key>patterns</key>
	<array>
		<dict>
	      <key>match</key>
	      <string>\#.*</string>
	      <key>name</key>
	      <string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(&lt;|&lt;\=|\=|&gt;|&gt;\=|&lt;&gt;|eq|ne|gt|ge|lt|le)\b</string>
			<key>name</key>
			<string>keyword.operator.comparison.python</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(spanning-tree|protocol|interface|lacp|port-channel|vlan|vrf|ip|dcb|lldp|mlag-vip|hostname|logging|username|radius-server|aaa|snmp-server|banner|WARNING|or|flowcontrol|cli|ntp|web|ssh|mlag-channel-group|channel-group|switchport)\b</string>
			<key>name</key>
			<string>keyword.directive.module</string>
		</dict>
		<dict>
	      <key>begin</key>
	      <string>\b(description)\b</string>
	      <key>captures</key>
	      <dict>
	        <key>1</key>
	        <dict>
	          <key>name</key>
	          <string>keyword.directive.nginx</string>
	        </dict>
	      </dict>
	      <key>end</key>
	      <string>\n</string>
	      <key>patterns</key>
	      <array>
	        <dict>
	          <key>include</key>
	          <string>#values</string>
	        </dict>
	      </array>
	      <key>name</key>
	      <string>punctuation.definition.variable</string>
	    </dict>
		<dict>
			<key>match</key>
			<string>\b(load-balance|mlag-port-channel|ethernet|name|name-server|bpdufilter)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
				<dict>
			<key>match</key>
			<string>\b(speed|mtu|receive|force|send|on|mode|active|hybrid|trunk|shutdown|lacp-individual)\b</string>
			<key>name</key>
			<string>punctuation.definition.variable</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\b(disable|enable)\b</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(no)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>

        <dict>
        <key>begin</key>
        <string>"</string>
        <key>endCaptures</key>
        <dict>
            <key>0</key>
            <dict>
                <key>name</key>
                <string>punctuation.definition.string.end</string>
            </dict>
        </dict>
        <key>beginCaptures</key>
        <dict>
            <key>0</key>
            <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin</string>
            </dict>
        </dict>
        <key>name</key>
        <string>string.quoted.double.dosbatch</string>
        <key>end</key>
        <string>"</string>
    </dict>
    <dict>
		<key>captures</key>
		<dict>
			<key>1</key>
			<dict>
				<key>name</key>
				<string>punctuation.definition.comment.sql</string>
			</dict>
		</dict>
		<key>match</key>
		<string>(\*).*$\n?</string>
		<key>name</key>
		<string>comment.line.number-sign.sql</string>
	</dict>
	</array>
	<key>scopeName</key>
	<string>source.cos</string>
	<key>uuid</key>
	<string>1BA75B32-707C-11D9-A928-000D98989AF6</string>
	</dict>
</plist>
